### DISCUSSION TITLE
How to suppress CSS comment syntax error?

### DISCUSSION THREAD

**Discussion by erosman** [microsoft/monaco-editor#4883] [Q&A]
Is there a way to suppress the following syntax error?
_(I was able to suppress the error in CodeMirror )_

Setting language to SCSS and using `// ....` didn’t help.
All suggestions are welcomed.

```css
/*
==UserCSS==
@name           Github
@match          https://github.com/*/issues*
@version        1.0
==/UserCSS==
*/

body {
  border: 1px solid red;
}
```

PS. How do you change the language on playground?
