### ISSUE TITLE
Bogus navigation on a change if the top of the editor is not visible

### ISSUE THREAD

**Issue by akosyakov** [Microsoft/monaco-editor#113]
Steps to reproduce:
1. go to: https://microsoft.github.io/monaco-editor/
2. scroll down to the diff editor
3. minimize your window that you don't see first 5 lines of the diff editor
4. change content of the last visible line, actually can be any, but for a dramatic effect :)
5. unexpectedly the top of the diff editor will be revealed

It really hurts in the case with auto resizing: https://github.com/Microsoft/monaco-editor/issues/103.

**Comment by alexandrudima** [comment]
I know I have code for detecting this browser reveal logic and undoing it when you click in the editor, I guess browsers desperately try to reveal the top-left textarea even when you type. 

One workaround would be to select the textarea and make it position:fixed.

```css
 .monaco-editor .inputarea { position: fixed !important; top: 0 !important; left: 0 !important; }
```
