### ISSUE TITLE
Support placeholder when content is empty

### ISSUE THREAD

**Issue by cwtuan** [microsoft/monaco-editor#1228]
Since `placeholder` isn't supported currently, is there any workaround?

**Comment by cwtuan** [comment]
any updated?

**Comment by BeginVic** [comment]
+1

**Comment by Tinysymphony** [comment]
I have the same question

**Comment by hiraditya** [comment]
When are we getting this feature?

**Comment by LironHazan** [comment]
I will also be happy to have it (if there's anything I can do to help LMK)

**Comment by sanket03** [comment]
Any updates folks?

**Comment by LironHazan** [comment]
This could be easily workaround by faking a placeholder, not saying that it's optimal but definitely a legit solution 

e.g. my implementation in an Angular  app:

```angular
<div *ngIf="!editorState.text" class="placeholder" (click)="focusOnEmptyText()">
  <div class="placeholder-text"> {{placeholder}} </div>
</div>  
```

```css

  @keyframes fadeIn {
    from { opacity: 0; }
    to   { opacity: 1; }
  }

  .placeholder {
    position: absolute;
    font-family: Lato;
    font-style: italic;
    color: var(--input-border-color);
    top: 8px;
    left: 34px;
    animation: fadeIn 500ms;
    animation-timing-function: ease-out;
  }
```
