### ISSUE TITLE
Monaco Editor Height Default Fit Container

### ISSUE THREAD

**Issue by HecticHiccups** [microsoft/monaco-editor#1476]
**monaco-editor version:** 0.17.0
**Browser:** Chrome
**OS:** Windows

**Steps or JS usage snippet reproducing the issue:**

> Here's a mockup of what I'm trying to accomplish on my Razor Page in .NET https://codepen.io/HecticHiccups/pen/zVOggP

> My current styling that renders in the image below. 
```css
#app {
    height: 100% !important;
    width: 100% !important;
    background-color: red;
}

#root {
    border: 2px solid blue;
    left: 0;
    top: 0;
    height: 100% !important;
    width: 100% !important;
    margin: 0;
    padding: 0;
    overflow: hidden;
}

#root > * {
     height: 100% !important; /*Temporary Fix: height: 100vh !important; */
     width: 100%;
}
```
> The editors dimensions defaults to 1300 x 5 & doesn't resize.
![monaco-height-issue](https://user-images.githubusercontent.com/11451777/59290128-da9f0f00-8c45-11e9-8f99-a4e660fc4526.PNG)

> Temporary Fix using the commented styling above.
![heightFix](https://user-images.githubusercontent.com/11451777/59291399-c577af80-8c48-11e9-963d-0a09cce61cb6.PNG)

## Todo List:
- [ ]  I want to be able to have the editor resize to fit it's container similar to how my codepen works.
