### ISSUE TITLE
Monarch indented block end

### ISSUE THREAD

**Issue by Tronic** [microsoft/monaco-editor#1564]
A few languages use indented blocks for structure, and thus don't always have end markers that could be directly matched against. In particular, YAML presents multi-line string literals (scalars in YAML terminology) in this way. The problem is that neither TextMate nor Monarch appear to support matching the change of indent, and consequently YAML's handling is quite broken in most editors.

````yaml
parent:
  textNode: |
    this is
    *** supposed to
    be:
    raw text
  anotherNode: foo
````

This could be solved primarily by
- explicit support for tracking indented blocks (alike the built-in brace tracking), or
- being able to use a previously captured indentation whitespace string in the end regex or otherwise to determine whether the block needs to be popped

Unless I've overlooked something, the current best solution is generating about 40 duplicate rules with all typically used indentation widths in their begin/end regular expressions.
