### ISSUE TITLE
The `overflow: hidden` CSS in the playground may have misleading effect

### ISSUE THREAD

**Issue by chenxinyanc** [microsoft/monaco-editor#1588]
https://github.com/microsoft/monaco-editor/blob/14f6229243233f456eb688c0dbdf505c61731b64/website/playground/playground-runner.html#L11

This line forces monaco editor to clip any children, including intellisense pop-ups. This is a) not 
what `monaco-editor` behaves in the wild; b) undesirable in some cases, especially when there are multiple editors on the same page (i.e. editor does not take up to 100% of the container).

So could you please consider removing this CSS rule, or at least moving it to the "CSS" tab so we know there is a CSS rule already applied?

### Actual behavior
Open https://microsoft.github.io/monaco-editor/playground.html, and replace the "HTML" tab with
```html
<div id="container" style="width: 300px; height: 200px; border: 1px solid;"></div>
```
![temp](https://user-images.githubusercontent.com/50703224/65145425-23881000-da4c-11e9-9246-0700fdeabd54.gif)

### Expected behavior
Do the same as "Actual behavior", plus replacing "CSS" tab with
```css
#container .monaco-editor {
    /* Override the CSS rule in https://microsoft.github.io/monaco-editor/playground/playground-runner.html */
    overflow: unset;
}
```
![temp](https://user-images.githubusercontent.com/50703224/65145801-f851f080-da4c-11e9-844f-a5d759107517.gif)
