### ISSUE TITLE
Monaco's underlying textarea, and content, can get out of sync when native undo is used

### ISSUE THREAD

**Issue by issacgerges** [microsoft/monaco-editor#1782]
**monaco-editor version:** 0.19.3
**Browser:** Chrome and Chromium
**OS:** MacOS

When using Chrome's system menus to undo/redo the `textarea` that backs monaco can become out of sync with the editor content.

### Repro
When unfocusing and recfocusing Chrome via `cmd+~`, the editor fails to respond to `undo` and `redo` events. I've added the following css to unhide the underlying `textarea`

```css
textarea.inputarea {
    width: 100px !important;
    color: white !important;
    background: rgb(150, 114, 236) !important;
};
```

![textarea-sync](https://user-images.githubusercontent.com/44379112/73130661-a64c4900-3fb1-11ea-99a4-c2cd4da884f5.gif)

### Suggestions
I'm unfamiliar with monaco but believe this issue could be fixed by also explicitly attaching a change handler to the `textarea` (which I've verified does fire in this case)
