### ISSUE TITLE
Horizontal scroll bar does not update properly for after-decoration

### ISSUE THREAD

**Issue by DrNiels** [microsoft/monaco-editor#2002]
**monaco-editor version:** 0.20.0
**Browser:** Chrome
**OS:** Windows 10
**Playground code that reproduces the issue:**
The example slightly modifies the existing example for line and inline decorations: https://microsoft.github.io/monaco-editor/playground.html#interacting-with-the-editor-line-and-inline-decorations

The CSS is changed to provide an after-decoration with a long text
```css
.myInlineDecoration::after {
    content: 'VeryLongTextVeryLongTextVeryLongTextVeryLongTextVeryLongTextVeryLongTextVeryLongText';
    color: green;
}

.myLineDecoration {
	background: lightblue;
	width: 5px !important;
	margin-left: 3px;
}
```

I would expect the horizontal scroll bar to appear as the line with the decoration is too long. However, I cannot scroll beyond the initally visible part and thus cannot see or modify the part at the back. When I add a line of text without decorations, the scroll bar will appear as intended.

**Comment by alexdima** [comment]
For ::before or ::after decorations, please use `beforeContentClassName` or `afterContentClassName` instead of `inlineClassName`.

e.g.

```css
.myInlineDecoration::after {
    content: 'VeryLongTextVeryLongTextVeryLongTextVeryLongTextVeryLongTextVeryLongTextVeryLongText';
    color: green;
}
```

```js
var jsCode = [
	'"use strict";',
	'function Person(age) {',
	'	if (age) {',
	'		this.age = age;',
	'	}',
	'}',
	'Person.prototype.getAge = function () {',
	'	return this.age;',
	'};'
].join('\n');

var editor = monaco.editor.create(document.getElementById("container"), {
	value: jsCode,
	language: "javascript"
});

var decorations = editor.deltaDecorations([], [
	{ range: new monaco.Range(7,1,7,24), options: { afterContentClassName: 'myInlineDecoration',  }},
]);
```

This allows the editor to realize that the monospace assumptions it is doing do not apply to that line:

![image](https://user-images.githubusercontent.com/5047891/92514273-e8a95a00-f211-11ea-9c11-13452a22e367.png)
