### ISSUE TITLE
Trailing annotation / decoration

### ISSUE THREAD

**Issue by bodinsamuel** [microsoft/monaco-editor#2075]
Hello team,

In vscode there is a possibility to add a trailing decoration to any line, not sure why it's not available into monaco but it would be awesome to have it.

It's notably used in the `vscode-gitlens` https://github.com/eamodio/vscode-gitlens/blob/30e1d290e8f337d56596a030ff097eeabdd98eb7/src/annotations/lineAnnotationController.ts

Thanks

**Comment by alexdima** [comment]
This is possible using `::after` or `::before` pseudo CSS selectors

e.g.

```css
.myInlineDecoration::after {
    content: 'VeryLongTextVeryLongTextVeryLongTextVeryLongTextVeryLongTextVeryLongTextVeryLongText';
    color: green;
}
```

```js
var jsCode = [
	'"use strict";',
	'function Person(age) {',
	'	if (age) {',
	'		this.age = age;',
	'	}',
	'}',
	'Person.prototype.getAge = function () {',
	'	return this.age;',
	'};'
].join('\n');

var editor = monaco.editor.create(document.getElementById("container"), {
	value: jsCode,
	language: "javascript"
});

var decorations = editor.deltaDecorations([], [
	{ range: new monaco.Range(7,1,7,24), options: { afterContentClassName: 'myInlineDecoration',  }},
]);
```
