### ISSUE TITLE
Hiding the cursor with CSS

### ISSUE THREAD

**Issue by felixfbecker** [microsoft/monaco-editor#2100]
#179 mentions that hiding the cursor is possible with CSS, but I couldn't find any docs on what CSS class is available to style the cursor. It's impossible to find out with dev tools unfortunately since the cursor disappears when the editor gets defocused.

**Comment by mofux** [comment]
It's somewhat hard to inspect because the cursor automatically hides once the editor gets unfocused, but you can hide the cursor via css like this:

```css
.monaco-editor .cursors-layer > .cursor {
	display: none !important;
}
```
