### ISSUE TITLE
monaco-aria-container shifting content in firefox

### ISSUE THREAD

**Issue by dsmmcken** [microsoft/monaco-editor#2168]
**monaco-editor version:** 0.21.2
**Browser:** firefox
**OS:** win/linux/probably mac but untested
**Playground code that reproduces the issue:**
https://codepen.io/dsmmcken/pen/dyMEvQR

Visit the above link in firefox, and open the find widget ctrl+f, so that the monaco-aria-container gains a value.

**Result:** The aria-container triggers overflow on the page, displaying firefox scrollbars in the 100% height container.

**Expected:** aria only content to not impact layout.

The monaco-aria-container is supposed to be hidden offscreen via:
```css
.monaco-aria-container {
	position: absolute; /* try to hide from window but not from screen readers */
	left:-999em;
} 
```
This doesn't fully work in firefox, and can break certain layouts, as shown in this test case. A recommended approach is something like:

```css
.screenreader {
    position: absolute !important; /* Outside the DOM flow */
    height: 1px; width: 1px; /* Nearly collapsed */
    overflow: hidden;
    clip: rect(1px 1px 1px 1px); /* IE 7+ only support clip without commas */
    clip: rect(1px, 1px, 1px, 1px); /* All other browsers */
}
```
https://stackoverflow.com/questions/26032089/in-html-how-can-i-have-text-that-is-only-accessible-for-screen-readers-i-e-fo
