### ISSUE TITLE
[firefox only] delta-decorations confuses IMouseTarget

### ISSUE THREAD

**Issue by jmue** [microsoft/monaco-editor#2175]
Using delta decorations which are rendered before or after the content causes mouse events where ```IMouseTarget.position``` is ```null``` and ```IMouseTarget.type``` is ```UNKNOWN.```

This is also affects monano playgrounds 'color-provider-example'. The color picker does not show up in firefox while hovering the colorbox.

**monaco-editor version:** 0.21.1
**Browser:** Firefox 81.0.1
**OS:** Windows 10
**Playground code that reproduces the issue:**

javascript:
```js
const editor = monaco.editor.create(document.getElementById("container"), {
    value: "one\ntwo"
});

const actions = editor.deltaDecorations([], [
    { range: new monaco.Range(1, 1, 1, 4), options: { afterContentClassName: 'redActionBox' } },
    { range: new monaco.Range(2, 1, 2, 4), options: { inlineClassName: 'blueActionBox' } },
]);

var output = document.getElementById('output');
function showEvent(str) {
    while (output.childNodes.length > 6) {
        output.removeChild(output.firstChild.nextSibling.nextSibling);
    }
    output.appendChild(document.createTextNode(str));
    output.appendChild(document.createElement('br'));
}

editor.onMouseMove(function (e) {
    showEvent('mousemove - ' + e.target.toString());
});
```

css:
```css
.redActionBox {
    border: 0.1em solid rgb(0, 0, 0);
    box-sizing: border-box;
    content: " ";
    background-color: rgb(255, 0, 0);
    margin: 0.1em 0.2em 0px;
    width: 0.8em;
    height: 0.8em;
    display: inline-block;
    cursor: pointer;
}

.blueActionBox::after {
    border: 0.1em solid rgb(0, 0, 0);
    box-sizing: border-box;
    content: " ";
    background-color: rgb(0, 0, 255);
    margin: 0.1em 0.2em 0px;
    width: 0.8em;
    height: 0.8em;
    display: inline-block;
    cursor: pointer;
}
```

html:
```html
<div id="container" style="height:70%;"></div>
<div style="background:#ccc;height:1%"></div>
<div id="output" style="height:29%;font-family:'Courier New', monospace;">Last 3 events:<br/></div>
```
