### ISSUE TITLE
afterContentClassName misses css content

### ISSUE THREAD

**Issue by jmue** [microsoft/monaco-editor#2176]
When using afterContentClassName for delta decorations, the styles content property is not transformed to the dom tree. See example below, althought both decorations are rendered behind, the first decoration misses the the text 'There is someting behind'.

**monaco-editor version:** 0.21.1
**Browser:** Firefox/81.0.1, Chrome/85.0.4183.121
**OS:** Windows 10
**Playground code that reproduces the issue:**

javascript:
```js
const editor = monaco.editor.create(document.getElementById("container"), {
    value: "one\ntwo"
});

const actions = editor.deltaDecorations([], [
    { range: new monaco.Range(1, 1, 1, 4), options: { afterContentClassName: 'redActionBox' } },
    { range: new monaco.Range(2, 1, 2, 4), options: { inlineClassName: 'blueActionBox' } },
]);
```

css:
```css
.redActionBox {
    border: 0.1em solid rgb(0, 0, 0);
    box-sizing: border-box;
    content: "There is something behind";
    background-color: rgb(255, 192, 192);
    margin: 0.1em 0.2em 0px;
    display: inline;
    line-height: 1em;
    cursor: pointer;
}

.blueActionBox::after {
    border: 0.1em solid rgb(0, 0, 0);
    box-sizing: border-box;
    content: "There is something behind";
    background-color: rgb(192, 192, 255);
    margin: 0.1em 0.2em 0px;
    display: inline;
    line-height: 1em;
    cursor: pointer;
}

```

html:
```html
<div id="container" style="height:100%;"></div>
```
