### ISSUE TITLE
Syntax Highlighting doesn't work properly with yaml

### ISSUE THREAD

**Issue by PrashantRaj18198** [microsoft/monaco-editor#2398]
Syntax highlighting only works in lines which are entirely comments or in lines which have quote string, it doesn't work with unquoted strings or integers.
This is a screenshot for monaco playground
![image](https://user-images.githubusercontent.com/23168997/111734906-07636a00-88a1-11eb-8c3d-edba78f6fc7e.png)
This is github code block with same yaml code
```yaml
# comments in seperate line works
quotedText: "this is quoted" #this comment has syntax highlighting
text: Pretty vector drawing. #this is comment doesn't have proper syntax higlighting
number: 3 #this comment also doesn't have proper syntax highlighting
```
