### ISSUE TITLE
zIndex doesn't seem to work for deltaDecorations

### ISSUE THREAD

**Issue by ColmanHumphrey** [microsoft/monaco-editor#2627]
**monaco-editor version:** 0.27.0 (from the playground)
**Browser:** Chrome 92.0.4515.131 (Official Build) (arm64)
**OS:** macOS Big Sur 11.3.1 M1
**Playground code that reproduces the issue:**

```js
var jsCode = `line1
line2
line3
line4`

var editor = monaco.editor.create(document.getElementById("container"), {
	value: jsCode,
	language: "javascript"
});

var decorations = editor.deltaDecorations([], [
	{ range: new monaco.Range(2, 2, 2, 6), options: { className: 'bgBlueBlackShadow', zIndex: 100 }},
	{ range: new monaco.Range(3, 2, 3, 6), options: { className: 'bgOrangeYellowShadow', zIndex: 1 }},
]);
```

```css
.bgBlueBlackShadow {
    background-color: skyblue;
    box-shadow: 0 0 0 2px black;
    border-radius: 0.25rem;
}

.bgOrangeYellowShadow {
    background-color: orange;
    box-shadow: 0 0 0 2px yellow;
    border-radius: 0.25rem;
}
```

## Result

We get the same as with no zIndex set: the bottom decoration beats the top:

<img width="134" alt="CleanShot 2021-08-20 at 18 24 27@2x" src="https://user-images.githubusercontent.com/6945891/130299041-ab9931f4-a5cd-4e9d-87cf-74497ef6f7b4.png">

## Expected

With the higher zIndex, I expected the skyblue decoration to sit on top of the orange one
