### ISSUE TITLE
Command Palette Text missing

### ISSUE THREAD

**Issue by windischb** [microsoft/monaco-editor#263]
I have problems with the Command Palette...
If i hit F1 i only see this:
![capture](https://cloud.githubusercontent.com/assets/6182311/20239894/93533bbe-a90b-11e6-82ff-02d0371ad5ab.JPG)

It looks like the Color of the the Text is missing or something.
I can scroll and select a Command, or type in the Textbox and press Enter.
Testet with Toggle and it works, but i can't see anything!
Same happens if i use another Theme....

Any suggestions?

monaco-editor npm version: 0.7.0
Browser: Chrome
OS: Windows 10

**Comment by alexandrudima** [comment]
Does this reproduce all the time for you? Can you provide a html page which reproduces the problem? (it is possible that some CSS from your page interferes with the widget).

**Comment by david50407** [comment]
Same problem here, even I tried add this css below, the command palette still blank (if the theme is dark, then it will be all dark; if the theme is vs, it will be all white)

css:
```css
* {
  color: #fff !important;
}
```

**Comment by david50407** [comment]
After adding this css, the list is back: 

```css
.monaco-tree-row * {
    display: initial;
}
```

But I want to find which css effected my command palette, is there any way to avoid hiding command palette from switching window? (I want to use inspector to check my css)

**Comment by apalsapure** [comment]
In my case, monaco css got overridden. This fixed the issue for me.
```css
.monaco-tree-rows .content {
   padding: 0;
   margin: 0;
}
.quick-open-widget .quick-open-tree .quick-open-entry > .row {
    margin: 0;
}
```

**Problem 1:**
I am using bootstrap 3 with monaco editor. Bootstrap adds -15px margin for class `row`, which causes text to appear cut. 

**Problem 2:**
I have css class named `content` which had padding. Monaco editor was rendered inside an element which had this class.

Hope this helps.
