### ISSUE TITLE
Decorations are improper on undo 

### ISSUE THREAD

**Issue by Pranomvignesh** [microsoft/monaco-editor#2784]
**monaco-editor version:** 0.30.1
**Browser:** Chrome
**OS:** Mac OS
**Playground code that reproduces the issue:**

### Javascript Code

```js
var jsCode = [
	'"use strict";',
	'function Person(age) {',
	'	if (age) {',
	'		this.age = age;',
	'	}',
	'}',
	'Person.prototype.getAge = function () {',
	'	return this.age;',
	'};'
].join('\n');

var editor = monaco.editor.create(document.getElementById('container'), {
	value: jsCode,
	language: 'javascript',
    fontSize : 20
});

var decorations = editor.deltaDecorations(
	[],
	[
		{
			range: new monaco.Range(7, 1, 7, 24),
			options: { inlineClassName: 'myInlineDecoration' }
		}
	]
);

```

### Styles 
```css
.myInlineDecoration {
  color: white !important;
  cursor: pointer;
  text-decoration: underline;
  font-weight: bold;
  font-style: oblique;
  background-color: blueviolet;
}
```

### Video Explaining the issue

https://user-images.githubusercontent.com/29809906/142765710-bafc834c-e00f-4c28-99a6-4a21ebbc8df0.mov

### Steps to Reproduce the issue
- Add a Decoration to a range
- Select a portion of the text containing the range
- Edit the selected range
- Now Undo the changes

Now the decorations are applied to the complete range instead of the original applied range

_PS : This issue was also reported in https://github.com/Pranomvignesh/constrained-editor-plugin/issues/4_
