### ISSUE TITLE
Suggestion box incorrectly offset with translate animated container

### ISSUE THREAD

**Issue by promeris** [microsoft/monaco-editor#2793]
When displaying monaco editor in a container that is slided into screen via translate animation, the suggestion box is offset incorrectly by (width of screen - width of container). Disabling the `fixedOverflowWidgets` option is not something we can do, as the suggestion box would be cut at editor length.

![Screenshot from 2021-11-25 14-24-45](https://user-images.githubusercontent.com/57860182/143449533-b69cec84-ad9c-438f-897e-d0a82ca686ca.png)

**monaco-editor version:** 0.30.0
**Browser:** Chrome Version 90.0.4430.93
**OS:** Ubuntu
**Playground code that reproduces the issue:**

```js
const container = document.createElement("div");
container.className = "container";

const monacoElement = document.createElement("div");
monacoElement.className = "monaco";

container.appendChild(monacoElement);
document.body.appendChild(container);
monaco.editor.create(monacoElement, {
    language: 'javascript',
    fixedOverflowWidgets: true,
});
```

```css
.container {
    width: 550px; /* increase/decrease to see offset change */
    height: 100vh;
    display: block;
    position: fixed;
    right: 0;
    bottom: 0;
    top: 0;
    border: 1px solid black;
    transform: translateX(100%);
    animation: translateAnimation 1s cubic-bezier(0.19, 1, 0.22, 1) both;
}

.monaco {
    width: 100%;
    height: 300px;
}

@keyframes translateAnimation {
    0% {
        transform: translateX(100%);
    } 100% {
        transform: translateX(0);
    }
}
```
