### ISSUE TITLE
Auto resize with contrainer

### ISSUE THREAD

**Issue by tylerlong** [Microsoft/monaco-editor#28]
``` css
html,body {
  margin: 0;
  padding: 0;
  height:100%;
}

#container {
  height: 100%;
}
```

The container always takes 100% of the page size. When I resize the page, however, the monaco editor doesn't resize itself.  I want the editor to resize itself so there will never be horizontal or vertical scroll bars.  I have done similar things with ACE and CodeMirror. Is it possible with monaco-editor?
