### ISSUE TITLE
Safari: Multi-overload signature help invisible with vscode 1.7.2

### ISSUE THREAD

**Issue by sandyarmstrong** [Microsoft/monaco-editor#282]
Safari 9.1.3 on OS X 10.11.6.
Monaco built with vscode 1.7.2 tag.

<img width="290" alt="invisisig" src="https://cloud.githubusercontent.com/assets/155076/20905077/3872a858-baf7-11e6-8406-8c8ff8f3da09.png">

Invoking signature help with multiple overloads now puts the signature content inside a scrollable element. The combination of `display:flex`, `overflow:hidden`, and `height:100%` breaks in Safari, but works fine in Chrome and Firefox. The signature content body ends up with 0 height and does not display.

Not yet sure what the real fix should be. One potential workaround is:

```css
.monaco-editor .parameter-hints-widget .monaco-scrollable-element {
  display: block !important;
}
```
