### ISSUE TITLE
[Bug] Wrong syntax highlighting for yaml

### ISSUE THREAD

**Issue by kenzyyang** [microsoft/monaco-editor#3221]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Additional Context

<img width="965" alt="image" src="https://user-images.githubusercontent.com/27340803/182118259-51fb366c-5db3-4be9-b53d-92a9047120b1.png">

In git
```yaml
hello: world#wrong syntax higlighting,it's not comment
hello1: world #it's comment
```

**Comment by kenzyyang** [comment]
hello ~ @hediet is this resolved ?

**Comment by lm-sec** [comment]
Can I hijack this issue? I have the same behavior in Monaco Editor playground, but not in VS Code. I also found another issue related to yaml comment syntax highlighting. The new issue is also only in the monaco editor playground, and not in VS Code. 

### Reproducible in vscode.dev or in VS Code Desktop?

- [x] Not reproducible in [vscode.dev](https://vscode.dev/) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ]  Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Code

#### JS: 

```javascript
monaco.editor.create(document.getElementById('container'), {
	value: "",
	language: 'yaml'
});
```

#### Yaml (shown here in GitHub is the expected behavior) :

```yaml
asdf: asdf#This is not a comment
asdf: asdf # This is a comment
asdf: asdf # This is a : comment with wrong highlight
```

### Reproduction Steps

Copy and paste the yaml above in a monaco editor playground configured with the above javascript.

### Actual (Problematic) Behavior

The comment's syntax highlighting is broken when the comment contains a `:`.

![image](https://user-images.githubusercontent.com/21041333/215351435-52bbef13-1dd3-4742-b95f-67a659244a66.png)

### Expected Behavior

GitHub has the expected syntax highlights: 

```yaml
asdf: asdf#This is not a comment
asdf: asdf # This is a comment
asdf: asdf # This is a : comment with wrong highlight
```

### Additional Context

#### Browser

Google Chrome Version 108.0.5359.124 (Official Build) (64-bit)

#### Monaco Editor

The version in the Monaco Editor right now, I assume `0.34.1`
