### ISSUE TITLE
[Bug] Multiple decorations per range rendered

### ISSUE THREAD

**Issue by yogabonito** [microsoft/monaco-editor#3224]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Reproduction Steps

1. As a starting point, I used [this playground example](https://microsoft.github.io/monaco-editor/playground.html#interacting-with-the-editor-line-and-inline-decorations)
2. In the CSS file, I added `border: 3px solid red;` to the `myInlineDecoration` class.
3. Press the `Run` button.

### Actual (Problematic) Behavior

There is a border around `Person` and _another one_ around `.prototype.getAge`.

![image](https://user-images.githubusercontent.com/7026269/182379100-6c9a3ac5-c64a-4ff8-87cc-a86bb481f281.png)

### Expected Behavior

I expected there to be only one border, as there is only _one_ `monaco.Range` in the JavaScript file specifying where the decoration should be.

### Additional Context

Could this behavior be a result of fixing issue #2626?

**Comment by hediet** [comment]
Thanks for reporting this!
Please copy all of the code from the example, so we can directly try to reproduce this bug. Thanks!

**Comment by yogabonito** [comment]
Here are the files from the playground:

### JavaScript

```js
var jsCode = [
	'"use strict";',
	'function Person(age) {',
	'	if (age) {',
	'		this.age = age;',
	'	}',
	'}',
	'Person.prototype.getAge = function () {',
	'	return this.age;',
	'};'
].join('\n');

var editor = monaco.editor.create(document.getElementById('container'), {
	value: jsCode,
	language: 'javascript'
});

var decorations = editor.deltaDecorations(
	[],
	[
		{
			range: new monaco.Range(3, 1, 5, 1),
			options: {
				isWholeLine: true,
				linesDecorationsClassName: 'myLineDecoration'
			}
		},
		{
			range: new monaco.Range(7, 1, 7, 24),
			options: { inlineClassName: 'myInlineDecoration' }
		}
	]
);
```

### CSS

```css
.myInlineDecoration {
    color: red !important;
    cursor: pointer;
    text-decoration: underline;
    font-weight: bold;
    font-style: oblique;
    border: 3px solid red; /* I only added this line */
}

.myLineDecoration {
    background: lightblue;
    width: 5px !important;
    margin-left: 3px;
}
```

### HTML

```html
<div id="container" style="height: 100%"></div>
```
