### ISSUE TITLE
[Feature Request] Get theme styles

### ISSUE THREAD

**Issue by jeremy-rifkin** [microsoft/monaco-editor#4031]
### Context

- [X] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [X] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

### Description

It'd be very helpful to be able to get the css declarations for classes used in editor and by the various colorize functions, e.g.:
```css
.mtk1 { color: #d4d4d4; }
.mtk2 { color: #1e1e1e; }
.mtk3 { color: #cc6666; }
.mtk4 { color: #9cdcfe; }
.mtk5 { color: #ce9178; }
.mtk6 { color: #b5cea8; }
.mtk7 { color: #608b4e; }
.mtk8 { color: #569cd6; }
.mtk9 { color: #dcdcdc; }
.mtk10 { color: #808080; }
.mtk11 { color: #7c9c7c; }
.mtk12 { color: #f44747; }
.mtk13 { color: #c586c0; }
.mtk14 { color: #a79873; }
.mtk15 { color: #dd6a6f; }
.mtk16 { color: #5bb498; }
.mtk17 { color: #909090; }
.mtk18 { color: #778899; }
.mtk19 { color: #ff00ff; }
.mtk20 { color: #b46695; }
.mtk21 { color: #ff0000; }
.mtk22 { color: #4f76ac; }
.mtk23 { color: #3dc9b0; }
.mtk24 { color: #74b0df; }
.mtk25 { color: #4864aa; }
.mtki { font-style: italic; }
.mtkb { font-weight: bold; }
.mtku { text-decoration: underline; text-underline-position: under; }
.mtks { text-decoration: line-through; }
.mtks.mtku { text-decoration: underline line-through; text-underline-position: under; }
```

Motivation: We use monaco's colorize functions in a couple places on [Compiler Explorer](https://godbolt.org/).
