### ISSUE TITLE
iconsInSuggestions doesn't work

### ISSUE THREAD

**Issue by xirzec** [Microsoft/monaco-editor#434]
monaco-editor version: 0.8.3

Set iconsInSuggestions to false in the editor config. Icons still show up in suggest widget. If you search through the code you can see a "no-icons" class gets added, but there doesn't appear to be any style rules to actually hide the icons.

**Comment by xirzec** [comment]
My current workaround:

```css
.monaco-editor .suggest-widget.no-icons .icon {
  display: none !important;
}
```
