### ISSUE TITLE
[Feature Request] Print monaco editor whole content

### ISSUE THREAD

**Issue by sytolk** [microsoft/monaco-editor#4787]
### Context

- [x] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [x] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

### Description

I try `window.print();` to print the whole content of monaco-ediotor but it print only the first page (visible with scoll page). I have try to remove scroll with:
```css
@media print {
    .monaco-editor, .monaco-editor div { /*.editor-scrollable*/
        overflow: visible;
    }
}
```
but without success.. Can we write css for `@media print` and maybe it's better to include it in library?

### Monaco Editor Playground Code

```typescript

```
