### ISSUE TITLE
How to Display Suggestions Upside Down

### ISSUE THREAD

**Issue by vlad-shatskyi** [microsoft/monaco-editor#560]
Hi. I'm working on a shell prompt, which is always at the bottom of the screen, meaning that suggestions will always be above the editor. Now, the problem is that the best match is furthest away from person's focus of attention. 

![image](https://user-images.githubusercontent.com/188928/29557946-45a8b72a-8733-11e7-949f-8142e7df857a.png)
It gets even worse if there are more suggestions. 

Is there a way to show them in reverse order? Even a private unstable API would be great.

**Comment by mofux** [comment]
The suggestion box usually opens to the bottom, unless it does not have enough space into that direction, which will cause it to open on the top.

Here is a very very very dirty css workaround that makes it work for your direction, but there may be side-effects:

```css
.monaco-editor .suggest-widget .monaco-list .monaco-list-row {
    position: relative !important;
    top: 0 !important;
}

.monaco-editor .suggest-widget .monaco-list-rows {
    display: flex;
    flex-direction: column-reverse;
    height: auto !important;
}
```

What it does is using the `flex` model on the suggestion container to reverse the column order. Usually, the columns are all positioned absolutely, I guess for a reason, which we have to disable to make this trick work.
