### ISSUE TITLE
Context menu has weird highlighting

### ISSUE THREAD

**Issue by JKillian** [Microsoft/monaco-editor#592]
monaco-editor version: 0.10.0
Browser: Chrome 61
OS: macOS Sierra

Right-click on editor in monaco playground in macOS and Chrome. The currently selected menu item renders oddly:

![image](https://user-images.githubusercontent.com/1400151/30817137-ff9693ec-a1e5-11e7-80a3-2cdbe32230f5.png)

This does not happen in Firefox, so might be a Chrome bug. Would be nice if we could work around it with different CSS in monaco though!

**Comment by troy351** [comment]
same problem on Windows 10, Chrome 61

**Comment by troy351** [comment]
seems it was caused by this
```css
.monaco-menu 
    .monaco-action-bar.vertical 
    .action-item .action-label:focus {
    color: #0059ac;
    stroke-width: 1.2px;
    text-shadow: 0 0 0.15px #0059ac;
  }
  .monaco-editor.hc-black
    .monaco-menu
    .monaco-action-bar.vertical
    .action-item
    .action-label:focus,
  .monaco-editor.vs-dark
    .monaco-menu
    .monaco-action-bar.vertical
    .action-item
    .action-label:focus {
    color: #acddff;
    stroke-width: 1.2px;
    text-shadow: 0 0 0.15px #acddff;
  }
```
in `editor.main.css`
