### ISSUE TITLE
Inline decorations cause cursor/mouse error

### ISSUE THREAD

**Issue by r24y** [Microsoft/monaco-editor#594]
monaco-editor version: 0.10.0
Browser: Chrome 63
OS: Mac OS
Steps or JS usage snippet reproducing the issue:

Adjusting CSS on an inline decoration causes the cursor position to be off. This occurs with several modifications, including:

- font size
- CSS `width` property
- Addition of pseudoelements

For instance, add this snippet to the CSS for the [line and inline decorations example](https://microsoft.github.io/monaco-editor/playground.html#interacting-with-the-editor-line-and-inline-decorations)

```css
.myInlineDecoration::before {
    content: '💥';
    margin: 0 3px;
}
```
