### ISSUE TITLE
Add Vertical line to line numbers ?

### ISSUE THREAD

**Issue by DevidCIC** [Microsoft/monaco-editor#877]
How can I add a vertical line to the line numbers just as in the image shown bellow?

![image](https://user-images.githubusercontent.com/26143044/40050021-91ad44cc-5836-11e8-9e49-e4dc0fbbddbe.png)

**Comment by alexandrudima** [comment]
You can try finding one of the dom nodes used by the editor (using browser tools) and styling it. e.g.

```css
.line-numbers {
    border-right: 1px solid red;
}
```
